theme = "rose_pine"

[editor]
mouse = false
cursorline = true
bufferline = "multiple"
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-inlay-hints = true

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "warning"
